### ISSUE TITLE
Compile issue at Protobuf-MinGW  ('strdup' was not declared)

### ISSUE THREAD

**Issue by Darrell666** [Ultimaker/cura-build-environment#11]
when running nmake I get the error:
```
D:\cura-build-environment-master\build\Protobuf-MinGW-prefix\src\Protobuf-MinGW\
src\google\protobuf\compiler\subprocess.cc:118:43: error: 'strdup' was not decla
red in this scope
   char* name_copy = strdup(program.c_str());

```
I assume its because __STRICT_ANSI__ is set, but I'm unsure how to best deal with the issue.  Is there an option on CMAKE, etc.  I remember in the past when running cmake in msys2 I got a warning about windows compatibility and setting an environmental variable to use some old mode, but I can't find/remember that info or whether it is relevant to fixing this issue.  Any suggestions?
                                           ^

**Comment by Ghostkeeper** [comment]
This seems to be a compile issue in our Protobuf dependency.

You can change CMake variables after running the cura-build-environment CMake by going into those subdirectories with CMake (point the source directory in CMake-GUI to that `D:\cura-build-environment-master\build\Protobuf-MinGW-prefix\src\Protobuf-MinGW` directory). Looking at [this](http://stackoverflow.com/questions/40766055/error-strdup-was-not-declared-in-this-scope) resource, I expect you might have to add something to the `CMAKE_CXX_FLAGS` or `CMAKE_C_FLAGS`. We depend on C++11 so the accepted answer in that StackOverflow question seems to apply to us as well.

**Comment by vgulatee** [comment]
Should we be implementing strdup in subprocess.cc

**Comment by Ghostkeeper** [comment]
Probably a bad idea, considering naming conflicts. But that's all up to the Protobuf developers to decide.

**Comment by IwalkerI** [comment]
Go to “src” dir and open “MakeFIle” replace all “-std=c++11” to “-std=gnu++0x”
