### ISSUE TITLE
Build fails on win64

### ISSUE THREAD

**Issue by markshancock** [Ultimaker/cura-build-environment#12]
When running nmake, most stuff works but PySerial fails to install and I can't get past that.

```
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[  6%] Built target OpenSSL
[ 14%] Built target Python
[ 14%] Performing install step for 'PySerial'
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --single-version-externally-managed not recognized
NMAKE : fatal error U1077: 'C:\Users\Mark\GitHub\cura-build-environment\build\$INSTALL_DIR\bin\python.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
```
If, however, I cd to PySerial-prefix\src\PySerial and run 'setup.py install' the install appears to work

When I then try to continue by typing 'nmake' from the build location, it trys again to install PySerial and fails as before (it must not recognize the install I did manually.

**Comment by markshancock** [comment]
Note: I am running Windows 10 Pro - 64bit

**Comment by markshancock** [comment]
OK, regarding the Sip issue, I am going to report it here.  It seems to have the same behavior (it runs when I do it manually using the info in the .make file).
Problem:
build proceeds pretty well (with a few complaints); but, then staring with siplib.c it can't find python.h
Manual build works
From the build area
```
cd Sip-prefix\src\Sip
configure.py --platform win32-msvc2015
nmake
```
Results:
Completes without error

Comparing the two builds, it looks like the include path in the 'cl' command is different:
CMake script `-IC:\Users\Mark\GitHub\cura-build-environment\build\NSTALL_DIR\include`
Manual nmake `-IC:\Users\Mark\AppData\Local\Programs\Python\Python35\include`

**Comment by markshancock** [comment]
OK, next thing that fails is Arcus because if can't find SIP
This seems related to [Ultimaker/cura-build#108](https://github.com/Ultimaker/cura-build/issues/108) and [Ultimaker/libArcus#51](https://github.com/Ultimaker/libArcus/issues/51)

**Comment by Ghostkeeper** [comment]
They seem to have some solutions in this StackOverflow question: http://stackoverflow.com/questions/14296531/what-does-error-option-single-version-externally-managed-not-recognized-ind

The guy saying `pip install --upgrade setuptools` looks promising.

**Comment by markshancock** [comment]
@Ghostkeeper good find.
I did the upgrade and it did take me to a newer version; but, since I am resolved PySerial manually, nmake no longer complains about the --single-version-externally-managed.
Right now I am stuck at Arcus "Could not find SIP".
I tried the removing the 'if win32' in FindSIP.py as described in the issue I referenced; but they did not resolve the issue.  I am still investigating but the message statements in FindSIP.py to see what is causing the return code, they do not show on the screen when I run it from nmake.  Any recommendations?

**Comment by DeepinDream** [comment]
hey @markshancock . I am stuck at the similar problem when install cx_Freeze. Is that the same as what you meet？
```
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

[  6%] Built target OpenSSL
[ 14%] Built target Python
[ 15%] Performing install step for 'cx_Freeze'
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --single-version-externally-managed not recognized
NMAKE : fatal error U1077: 'E:\Documents\cura-build-environment\build\$INSTALL_DIR\bin\python.exe' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Apps\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Apps\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by markshancock** [comment]
@DeepinDream, that is similar to what I ran into with PySerial.  I was able to get past it by manually executing the steps in the make file from the command line in the PySerial-prefix\src\PySerial directory.

First you may want to try upgrating setuptools are @Ghostkeeper recommended to see if that gets you past it easier.  Right now I am stuck at 'Arcus' due to another issue.

**Comment by LipuFei** [comment]
Looks like a problem with old `setuptools`.

**Comment by LipuFei** [comment]
Closing this because in the current `master` we use `pip install` to install most python packages.
