### ISSUE TITLE
Error reading 'cura.jinja' profile: Profile not found: default

### ISSUE THREAD

**Issue by seanlab1** [Ultimaker/cura-build-environment#127]
Hello
I have new enviroment with conan
and as following errors
=====
-- Conan executing: /home/ultimaker/.local/bin/conan install /home/ultimaker/ultimaker/cura-build-environment/conanfile.py -pr=default -g=cmake --build=missing
ERROR: Error reading '/home/ultimaker/.conan/profiles/cura_release.jinja' profile: Error reading 'cura.jinja' profile: Profile not found: default
CMake Error at build/conan.cmake:540 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  build/conan.cmake:882 (old_conan_cmake_install)
  cmake/conan.cmake:15 (conan_cmake_run)
  CMakeLists.txt:17 (include)

Is there any environment?

thanks

**Comment by jellespijker** [comment]
`conan profile new default --detect` should do the trick

**Comment by jellespijker** [comment]
I will update documentation to reflect this step in setting up Conan on a local computer

**Comment by jellespijker** [comment]
Updated the readme for this extra instruction after a fresh Conan install
