### ISSUE TITLE
Need a new release to fix Cura’s GitHub Actions

### ISSUE THREAD

**Issue by cclauss** [Ultimaker/cura-build-environment#131]
https://github.com/Ultimaker/cura-build-environment/blob/107774e00e2a87607703ce6baac6eb7113e66b3a/docker/linux/.env#L6-L7 is building a version of `cmake` that would fix the failing Cura workflows at https://github.com/Ultimaker/Cura/actions

**Comment by jellespijker** [comment]
The GitHub actions will be setup in a different way.

See https://github.com/Ultimaker/Curaengine/tree/CURA-9177_Fix_CI_CT
This script will also serve as a basis for Cura and CuraEngine.

The main difference is that we are moving away from this big huge CMakeScript and will now longer uses cura-build-environment.
But purely use GitHub runners and Conan coupled with pip as a CMake dependency

**Comment by jellespijker** [comment]
I will close this as a won't fix, because we are going to use the above mentioned approach.

In all likely hood the actions will keep on falling this week. But we're working on it. We finally got a bit of a breather after the beta release.
