### ISSUE TITLE
5.0 Windows requires conan user login, what are the details?

### ISSUE THREAD

**Issue by phedg1** [Ultimaker/cura-build-environment#154]
Hi,
I'm trying to compile the 5.0 cura-build-environment on Windows 10. It starts to work but then says the following, seemingly wanting a login to some service. What do I do here?

protobuf/3.17.1: Not found in local cache, looking in remotes...
protobuf/3.17.1: Trying with 'cura'...
Please log in to "cura" to perform this action. Execute "conan user" command.
Remote 'cura' username: | it is waiting for input here |

These are the steps I've taken.
I've installed python 3.10.2, conan (latest at the time of writing), visual studio 2022 x64 with the desktop c++ package (to get NMake), docker and NSIS (to get makensis).

I've opened visual studio, opened the developer command prompt in visual studio, changed the directory to the new build folderI created in the project. Then created the default conant profile with "conan profile new default --detect" and downloaded the cura conan profiles with "conan config install https://github.com/ultimaker/conan-config.git".

I've then run "cmake -G "NMake Makefiles" -DCMAKE_PREFIX_PATH="C:\Users\Peter\Documents\3D Print\_Software\cura-build-environment\build\install" -DCMAKE_INSTALL_PREFIX="C:\Users\Peter\Documents\3D Print\_Software\cura-build-environment\build\install" .." to get it to compile. This is when a bunch of output is displayed ending with the login situation.

**Comment by jellespijker** [comment]
Use the 5.1 branch from the Cura repo. This repository is end-of-life. See this PR for more detailed instructions https://github.com/Ultimaker/Cura/pull/12544

Also make sure you remove the cura remote since that is the one that requires a authentication. It will then default to cura-ce

You can remove the cure remote with the following command.
```
conan remote remove cura
```

We will update the documentation as soon as possible, to reflect all the new changes

**Comment by phedg1** [comment]
@jellespijker Would this new combined version still allow for the CuraEngine and Cura repos to be modified? I'm just trying to add some new raft functionality and get it to compile, so I can use it in the Cura program... Been trying for days...

**Comment by jellespijker** [comment]
Yes it would. I'm in the process of updating the documentation, should probably be up to date somewhere tomorrow

**Comment by jellespijker** [comment]
See https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source
For a more detailed set of instructions. Still WIP atm.

**Comment by phedg1** [comment]
So, I still have not had any luck with this in any version yet. I could not get this cura build environment working on windows 10 with the 5.0 branch. I could not get the cura project working with the instructions in that new wiki page you linked me to on the 5.1 branch. Are you able to inform me how I can get this working for either project? For the cura 5.1thing I get the following error:
ERROR: Unable to find 'cura/5.1.0' in remotes
