### ISSUE TITLE
The CMake policy CMP0091 must be NEW? How to deal with it

### ISSUE THREAD

**Issue by yess1987** [Ultimaker/cura-build-environment#158]
-- Using Conan toolchain: C:/cura-build-environment/build/conan_toolchain.cmake
CMake Error at C:/cura-build-environment/build/conan_toolchain.cmake:32 (message):
  The CMake policy CMP0091 must be NEW, but is ''
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:1 (project)

CMake Error: CMake was unable to find a build program corresponding to "NMake Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
-- Configuring incomplete, errors occurred!
NMAKE : fatal error U1077: “echo”: 返回代码“0x1”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"”: 返回代码“0x2”
Stop.

**Comment by jellespijker** [comment]
This repo is being deprecated in favor of our new build process. See https://github.com/Ultimaker/cura-build-environment/pull/157

There are also links to documentation in the Wiki how to build Cura from source,
