### ISSUE TITLE
Fix needed in comtypes

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/cura-build-environment#18]
Found a commit, which applied here on my own and which fixed the execution of a function.
Could you please apply it here?

https://github.com/enthought/comtypes/commit/7d66f3e0586f5e467764d57a252e09fc4e05270c

**Comment by Ghostkeeper** [comment]
Tried this but I had to revert because my build didn't work out quite well :(

**Comment by thopiekar** [comment]
Don't get the issues anymore and/or can't remember what the issue was.
Thus,,
