### ISSUE TITLE
Need win32file.GetLongPathName to convert DOS 8.3 paths

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/cura-build-environment#19]
Need it for the SolidWorks plugin.

**Comment by Ghostkeeper** [comment]
Doesn't this work?

    import ctypes
    path = "C:\Progra~1"
    buffer = ctypes.create_unicode_buffer(1024)
    ctypes.windll.kernel32.GetLongPathNameW(path, buffer, 1024)
    print(buffer.value)

Could someone run that on a Windows computer?

**Comment by LipuFei** [comment]
It works for me

**Comment by LipuFei** [comment]
From the documentation (https://msdn.microsoft.com/en-us/library/windows/desktop/aa364980(v=vs.85).aspx) of `GetLongPathNameW()`, looks like the full path can go up to 32,767 wide characters. 1024 for a path on Windows is not enough according to my experience. 4096 would be a better choice.

**Comment by LipuFei** [comment]
@thopiekar Oh, now I see this is for detection SolidWorks installation path. As mentioned in https://github.com/Ultimaker/CuraSolidWorksPlugin/pull/18, `wmic` can get the full path. If we want to use `wmic`, then we don't need `win32file`.

**Comment by thopiekar** [comment]
Hmm, hard to decided at this point. In my point of view, but lead to the same result.
On the one hand we are calling wmic and on the other side we are using a windll.
Question is: Are there cases, where you don't have wmic installed? Does it come with each Windows distribution? Is it possible that users can remove the PATH, where it is installed, so our plugin won't be able to find it?

**Comment by LipuFei** [comment]
AFAIK, wmic is on Windows 7 at least. I will check if it's one XP and Vista.

**Comment by awhiemstra** [comment]
You do not need to check XP as we have never supported that with Cura 2.

**Comment by LipuFei** [comment]
Just checked MS documentation: https://msdn.microsoft.com/en-us/library/aa394531(v=vs.85).aspx
The minimum support for `wmic` is Vista. So we are lucky :) @awhiemstra @thopiekar
