### ISSUE TITLE
Build fails on macOS 10.13 as Qt 5.8.0 requires patches

### ISSUE THREAD

**Issue by d235j** [Ultimaker/cura-build-environment#22]
Looks like Qt 5.8.0 requires the following patches to build on macOS 10.13 (and Qt is not planning to issue a patch release with this). It seems Qt is pushing customers to use the LTS releases instead (5.6.x or 5.9.x), which are supported for 3 years and get more frequent patch releases.

https://bugreports.qt.io/browse/QTBUG-62266

**Comment by d235j** [comment]
Upgrading to Qt 5.9.2 would solve this problem but then we'd run into this: https://github.com/Ultimaker/Cura/issues/2596

**Comment by Ghostkeeper** [comment]
We're not applying any patches on our build server though. I can't recall which MacOS version we're using there.

**Comment by LipuFei** [comment]
Our build system is OS X 10.11.6

**Comment by d235j** [comment]
Yeah — this issue only involves building on 10.13 as Apple removed more legacy symbols from their SDK headers.

**Comment by LipuFei** [comment]
Hi @d235j , we have moved to Qt 5.10.1 + PyQt 5.10 for some time. Because this issue is related to Qt 5.8.0, I'm closing it now. You can try the new Qt version.
