### ISSUE TITLE
Build fails on newer versions of macOS if Xcode Command Line Tools are not installed

### ISSUE THREAD

**Issue by d235j** [Ultimaker/cura-build-environment#23]
On newer versions of macOS, Python cannot find the zlib headers cannot be found unless the Xcode Command Line Tools are first installed, as macOS no longer comes with a populated `/usr/include`.
In order to install these, one must run `xcode-select --install`.

**Comment by Ghostkeeper** [comment]
Should we update our instructions for MacOS then?

**Comment by d235j** [comment]
@Ghostkeeper Yeah I'd suggest this be done.

**Comment by Ghostkeeper** [comment]
Thanks for the suggestion. I've added it to the readme.
