### ISSUE TITLE
Docker - how to use the environment for building

### ISSUE THREAD

**Issue by cncpadawan** [Ultimaker/cura-build-environment#41]
Hello,

Sorry for the very dumb question.. but I followed the instructions for setting up the docker image, but from there I am not sure how to build in the environment.  I created a container using the image and ran bash.. but cmake isn't in the paths or in the filesystem, so I can't kick off the build process.  Is there some sort of a walk through on building using it?

Again, sorry for the dumb question (I haven't used docker before)...

**Comment by ChrisTerBeke** [comment]
You shouldn't need cmake on your host machine to use the docker image. Simply install Docker, run the provided command to build the image (can take a long time) and after that use `docker run -it <image_name>` to run the image. This won't give you a full Cura setup though. The Dockerfile in the Cura repo (https://github.com/Ultimaker/Cura/blob/master/Dockerfile) is building on top of this image to actually run Cura.

**Comment by cncpadawan** [comment]
Hello ChrisTerBeke,

Thanks for the info.  I did run the command, it built the image, and I started the image, but from there I'm not exactly sure what to do with it from there.  My understanding from the readme is that it should create a build environment.. is that not the case?

**Comment by ChrisTerBeke** [comment]
The image in this repository IS the build environment. Please check the Cura repository for a Docker image that is build on top of it.
