### ISSUE TITLE
env win32.bat bug

### ISSUE THREAD

**Issue by BrentHuang** [Ultimaker/cura-build-environment#45]
call "C:\Program Files\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

shoule be：

call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

**Comment by thopiekar** [comment]
Sure? So you have a 32bit install of Windows?
I thought there is no "Program File (x86)" on Windows 32bit, only on 64bit.

**Comment by LipuFei** [comment]
Hi @BrentHuang , thanks for the report. I've just fixed it in fb726c0. We are only working on the 64-bit environment on Windows and the 32-bit hasn't been touched for a very long time, so I can't guarantee that it still works.
