### ISSUE TITLE
[master] help needed to build on Windows

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/cura-build-environment#48]
I am trying to build on a Windows 10 VM using the 2017 VS Community edition. I have altered env_win64.bat to have this:
````
call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
````

And I have also added this:

````
set VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140
````

The python build fails with these messages:

````
C:\Users\burto\cura\cura-build-environment\build\Python-prefix\src\Python>msbuild "C:\Users\burto\cura\cura-build-environment\build\Python-prefix\src\Python\PCbuild\pcbuild.proj" /t:Build  /nologo /v:m /p:Configuration=Release /p:Platform=x64 /p:IncludeExternals=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:UseTestMarker=
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.Cpp.Current.targets(64,5): error MSB4062: The "SetEnv"
 task could not be loaded from the assembly C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.Build.CppT
asks.Common.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, Pu
blicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the
<UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contain
s a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\burto\cura\cura-build-environment\build\Pyt
hon-prefix\src\Python\PCbuild\pythoncore.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.Cpp.Current.targets(64,5): error MSB4062: The "SetEnv"
 task could not be loaded from the assembly C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.Build.CppT
asks.Common.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, Pu
blicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the
<UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contain
s a public class that implements Microsoft.Build.Framework.ITask. [C:\Users\burto\cura\cura-build-environment\build\Pyt
hon-prefix\src\Python\PCbuild\python3dll.vcxproj]
````

Any idea how to fix this?

**Comment by LipuFei** [comment]
Hi @smartavionics , for Python 3.5, we use VS 2015 to build. I don't know if VS 2017 works for Python 3.5, but Python 3.6 definitely needs VS2017. I have an experimental branch for that called "py3.6"

**Comment by smartavionics** [comment]
Hi, does your experimental branch work?!

**Comment by smartavionics** [comment]
I am trying that py3.6 branch but it keeps wanting to build a 32 bit version of something and I can't find a way to make it build a 64 bit version:
````
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.15.26730.0
-- The CXX compiler identification is MSVC 19.15.26730.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building for 32-bit Windows
-- Found Subversion: C:/Program Files/SlikSvn/bin/svn.exe (found version "1.9.7")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/burto/cura/cura-build-environment/build
````

**Comment by LipuFei** [comment]
You need to add this flag to CMAKE `cmake -DBUILD_OS_WIN64=ON`. Last time I checked, it seems to be a bug in CMake that it can't detect 64-bit Windows correctly somehow with VS2017

**Comment by LipuFei** [comment]
BTW, there are other things to look out for, I'll put what I remember:

Make sure you have the correct environment variables through out the whole building process. For example, you need to make sure that Python is built and the rest of the components are built using the Python you just built. What I did was something like this:

```
call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"

set PATH=${environment_dir}\\bin;%PATH%
set PATH=${environment_dir}\\scripts;%PATH%
set PATH=${environment_dir};%PATH%

cmake -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_PREFIX_PATH=${environment_dir} \
    -DCMAKE_INSTALL_PREFIX=${environment_dir} \
    -DBUILD_OS_WIN64=ON \
    -G "NMake Makefiles" \
    ${env_root_dir}\\src

nmake
```

**Comment by smartavionics** [comment]
Thanks for that, I have done similar and got a lot further, python, numpy, etc. built. Currently working on protobuf...

**Comment by smartavionics** [comment]
Currently stuck on this...
````
Scanning dependencies of target Protobuf-MinGW
[ 89%] Performing configure step for 'Protobuf-MinGW'
CMake Error at C:/Program Files/CMake/share/cmake-3.12/Modules/CMakeMinGWFindMake.cmake:12 (message):
  sh.exe was found in your PATH, here:

  C:/Program Files/Git/bin/sh.exe

  For MinGW make to work correctly sh.exe must NOT be in your path.

  Run cmake from a shell that does not have sh.exe in your PATH.

  If you want to use a UNIX shell, then use MSYS Makefiles.
````

Thing is, sh.exe is not on the PATH, so I don't know how it is finding the above.

**Comment by LipuFei** [comment]
For this one, you need to run `mingw32-make` twice and the second time it will work. The Windows build system we have uses cygwin which doesn't have this problem, but I have this problem on my laptop. And running that twice is how I solved it...

**Comment by smartavionics** [comment]
Great progress, I've got all the way to creating the files in the build\package directory.

However, I don't get an installer created. Is that done manually or what?

**Comment by thopiekar** [comment]
You need to run "mingw32-make package"

**Comment by LipuFei** [comment]
The installer is created separately with the repository https://github.com/Ultimaker/cura-build.

**Comment by smartavionics** [comment]
Hi guys, thanks for all the help. Running make package is what I needed to do. It took forever but I now have an installer which I will test tomorrow. Haven't a clue whether it will run or not but if you want to try it out it's in https://www.dropbox.com/s/dckbkpqyjsal083/Cura-mb-master-20181004-win64.exe?dl=0

**Comment by lamest** [comment]
hello,
this seems the right place to ask.
I also trying to build on windows, but with vcppbuildtools 2015. Somebody there should know how to deal with this error:

`C:\cura-build-environment\build\Python-prefix\src\Python>msbuild "C:\cura-build-environment\build\Python-prefix\src\Python\PCbuild\pcbuild.proj" /t:Build  /nologo /v:m /p:Configuration=Release /p:Platform=x64 /p:IncludeExternals=true /p:IncludeSSL=true /p:IncludeTkinter=false /p:UseTestMarker=
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\cura-build-environment\build\Python-prefix\src\Python\PCbuild\pythoncore.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.Cpp.Platform.targets(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\cura-build-environment\build\Python-prefix\src\Python\PCbuild\python3dll.vcxproj]
[  3%] Performing install step for 'Python'
arch amd64
source C:\cura-build-environment\build\Python-prefix\src\Python
dest C:\ultimaker\cura-build-environment\3.5
bindir C:\cura-build-environment\build\Python-prefix\src\Python\PCbuild\amd64
Install binaries to DESTDIR/bin
C:\cura-build-environment\build\Python-prefix\src\Python\PCbuild\amd64\python.exe
The system cannot find the path specified.
The system cannot find the path specified.
Install libraries to DESTDIR/lib
The system cannot find the path specified.`

**Comment by smartavionics** [comment]
Good Morning. I tried the installer I made last night and it was partially successful. Cura can be opened but there are two obvious problems:

1 - there are no icons

2 - the settings pane is missing - I looked at the log and there was an error loading a dll (qtquickcontrols2plugin.dll) and also messages saying that SVG format wasn't recognised.

[stdout.log](https://github.com/Ultimaker/cura-build-environment/files/2449305/stdout.log)
[stderr.log](https://github.com/Ultimaker/cura-build-environment/files/2449306/stderr.log)

**Comment by LipuFei** [comment]
@smartavionics Is this build with Python 3.6 or 3.5 (master)?

**Comment by smartavionics** [comment]
python 3.6.

**Comment by LipuFei** [comment]
Hi @lamest , from log it says that it cannot find VS 2010, but you intended to build with 2015. They don't match. I don't know what happened, but could you make sure that you have the correct setup for VS 2015 so a program won't get confused and try to find VS 2010 instead? And are you trying the `master` branch of `cura-build-environment`?

**Comment by LipuFei** [comment]
@smartavionics The `py3.6` branches are not up-to-date at the moment. They don't include the latest changes in `master`. I will update them later.

For the missing `qtquickcontrols2plugin.dll`, could you check if this DLL exists in your build environment at all? If so, you can copy it to the Cura installation and see if it works. If it's simply not included in the installer, it should be fixed in https://github.com/Ultimaker/cura-build

For the missing SVG support, it chould be that the SVG support wasn't compiled for Qt because when Qt was configured, it didn't find the SVG library it depends on. But, I just checked the qt-5.10.1 configuration help and I didn't find any SVG related options, so I also doubt that's the case... For this one, you could try to install `PyQt5 5.10` directly from `pip`, which will be a precompiled version:
```
${your-env-dir}/bin/python3.6 -m pip install --force PyQt5.10
```

**Comment by LipuFei** [comment]
A difference between py3.6 and master is that master installs PyQt5 via pip directly which is a pre-compiled version, while in py3.6, we compile both Qt and PyQt5, so something can go wrong there.

**Comment by smartavionics** [comment]
That dll is installed into qml/QtQuick.2 so I don't know why the plugin couldn't find it.

The biggest problem is the lack of settings pane. Are these messages relevant?
````
2018-10-05 08:12:14,531 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [352]: file:///C:/Program Files/Ultimaker Cura master/resources/qml/Topbar.qml:19:
 TypeError: Cannot read property 'stageId' of null
2018-10-05 08:12:14,539 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [352]: file:///C:/Program Files/Ultimaker Cura master/resources/qml/Topbar.qml:104
: TypeError: Cannot read property 'stageId' of null
2018-10-05 08:12:14,546 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [352]: file:///C:/Program Files/Ultimaker Cura master/resources/qml/Topbar.qml:175
: TypeError: Cannot read property 'stageId' of null
2018-10-05 08:12:14,553 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [352]: file:///C:/Program Files/Ultimaker Cura master/resources/qml/Cura.qml:445: 
TypeError: Cannot read property 'mainComponent' of null
2018-10-05 08:12:14,560 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [352]: file:///C:/Program Files/Ultimaker Cura master/resources/qml/Cura.qml:439: 
TypeError: Cannot read property 'mainComponent' of null
2018-10-05 08:12:14,567 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [352]: file:///C:/Program Files/Ultimaker Cura master/resources/qml/Cura.qml:477: TypeError: Cannot read property 'sidebarComponent' of null
2018-10-05 08:12:14,574 - WARNING - [MainThread] UM.Qt.QtApplication.__onQmlWarning [352]: file:///C:/Program Files/Ultimaker Cura master/resources/qml/Cura.qml:509: TypeError: Cannot read property 'sidebarComponent' of null
````

**Comment by LipuFei** [comment]
With the current master running from source code, I also see those warnings, so I don't think they are relevant.

**Comment by LipuFei** [comment]
@smartavionics We are pretty busy with Cura things lately so my apologies in advance that I may not have a lot of time checking issues here.

**Comment by smartavionics** [comment]
That's OK, understood. There's no urgency in this. It would just be nice to be able to create Windows releases of my development builds as most people are using that platform.

**Comment by LipuFei** [comment]
I would recommend to create another Windows VM with VS 2015, so you can create builds with the current master branches. That's what we use for releases so it's pretty much guaranteed to work, and you can have all the latest changes.

**Comment by smartavionics** [comment]
OK, thanks, I'll try that.

**Comment by lamest** [comment]
@LipuFei i was trying to build with build tools without full visual studio. Is it supposed to be working?

all i did is
` visualcppbuildtools_full.exe -NoRestart -Quiet -NoWeb `
and 
`cd cura-build-environment && mkdir build && cd build && "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 && set CRYPTOGRAPHY_WINDOWS_LINK_LEGACY_OPENSSL=1 && cmake .. -DCMAKE_INSTALL_PREFIX=C:/ultimaker/cura-build-environment/3.5 -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" -DINCLUDE_DEVEL=ON && nmake`

also didn't use `env_win64.bat` because it trying to add `-m64` which is seems irrelevant on x64 cl.exe

I was trying ` 3.4.1`, `3.5` and `fb726c03c01d8c33e15605232b6af2234b1ade7c ` commits

**Comment by LipuFei** [comment]
For the `cmake` command, you also need to set `-DCMAKE_PREFIX_PATH==C:/ultimaker/cura-build-environment/3.5`

**Comment by LipuFei** [comment]
See https://github.com/Ultimaker/cura-build-environment/issues/48#issuecomment-427012693

> BTW, there are other things to look out for, I'll put what I remember:
> 
> Make sure you have the correct environment variables through out the whole building process. For example, you need to make sure that Python is built and the rest of the components are built using the Python you just built. What I did was something like this:
> 
> ```
> call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Auxiliary\\Build\\vcvars64.bat"
> 
> set PATH=${environment_dir}\\bin;%PATH%
> set PATH=${environment_dir}\\scripts;%PATH%
> set PATH=${environment_dir};%PATH%
> 
> cmake -DCMAKE_BUILD_TYPE=Release \
>     -DCMAKE_PREFIX_PATH=${environment_dir} \
>     -DCMAKE_INSTALL_PREFIX=${environment_dir} \
>     -DBUILD_OS_WIN64=ON \
>     -G "NMake Makefiles" \
>     ${env_root_dir}\\src
> 
> nmake
> ```

**Comment by smartavionics** [comment]
Hi @LipuFei , I realise you are busy so I don't want you to investigate this but I wonder if you have come across the following problem. I have managed to get a working build on a Windows 10 VM. On a Windows 10 laptop using the same VC, mingw, and other tools it gets all the way to the cx_Freeze stage and then fails with the following message.
````
[ 97%] Built target projects
running cx_Freeze
running build_exe
copying C:\Users\burto\cura\inst\lib\site-packages\cx_Freeze\bases\Win32GUI.exe -> package\Cura.exe
copying C:\Users\burto\cura\inst\bin\python35.dll -> package\python35.dll
error: [WinError 2] The system cannot find the file specified: 'package\\Cura.exe'
NMAKE : fatal error U1077: 'C:\Users\burto\cura\inst\bin\python.exe' : return code '0x1'
````
I can't work out why the build on the VM is working and the build on the laptop fails. Any thoughts?

**Comment by smartavionics** [comment]
I found the problem, I simply had not set PYTHONPATH to find the site packages in the inst dir.

Anyway, I can now build for all 3 platforms. It's been a nightmare!

Thanks again for your help.
