### ISSUE TITLE
Build Issue OSX Mojave: Cannot compute size of size_t

### ISSUE THREAD

**Issue by roseg0ld** [Ultimaker/cura-build-environment#51]
I am building on OSX Mojave, everything is working fine until I get to building Python. When I do I am getting the following:
`checking size of size_t... configure: error: in "/Users/Zach/Desktop/Hydra/cura-build-environment-master/build/Python-prefix/src/Python":
configure: error: cannot compute sizeof (size_t)
See "config.log" for more details
make[2]: *** [Python-prefix/src/Python-stamp/Python-configure] Error 7
make[1]: *** [CMakeFiles/Python.dir/all] Error 2
`

I am very new to this kind of development so if any more information is needed let me know. Any help resolving this issue would be very appreciated! I'm attaching the config.log 
[config.log](https://github.com/Ultimaker/cura-build-environment/files/2631367/config.log)

**Comment by roseg0ld** [comment]
Solved it my XCode Developer tools was incorrectly installed

**Comment by harveynr** [comment]
@roseg0ld @yzy65172846 Do either of you have more information?  I'm running into a similar issue on 10.14 and a reinstall of Xcode did not resolve it.  Thanks.

**Comment by roseg0ld** [comment]
I gave up building my own version of Cura and wrote a plugin to add the functionality I needed at the time; the dependency rabbit hole is very deep. 

Honestly, since it's been a few months I don't remember how I resolved this issue exactly, but it had to do with my installation of python, not developer tools. I believe there were some issues with pyenv, I solved it by sorting through my config log and googling the bit about **checking size of size_t...**

If I remember more I'll post it here, good luck!

**Comment by Ghostkeeper** [comment]
`size_t` should equal the memory address size on any modern computer. So if you have a 64-bit CPU then `size_t` should be 64 bits (8 bytes). The only exception to this is if you have segmented memory and an operating system that enforces allocations to be in the same segments, but that is very outdated so we didn't take that into account when programming CuraEngine.

**Comment by harveynr** [comment]
> I gave up building my own version of Cura and wrote a plugin to add the functionality I needed at the time; the dependency rabbit hole is very deep.
> 

Thanks, I am also working on a plugin so I think I'm going to work around the self-build as well, as it doesn't seem to be really crucial (though it would sure be nice for debugging).

**Comment by aharshac** [comment]
One way to solve this is by upgrading the SDK. 
I had the same problem with 10.7 SDK on 10.13.6, but get no errors with 10.10 SDK.

Change CURA_TARGET_OSX_VERSION and CURA_OSX_SDK_VERSION to something more recent.

**Comment by Ghostkeeper** [comment]
We're using a fairly ancient Macbook to build Cura for MacOS as well, which is running Mountain Lion as far as I know. I suppose that's why it does work for us.

**Comment by evtrados** [comment]
The problem occurs on Mojave versions onwards. The way to solve it is to remove the `--enable-universalsdk` configure parameter in the  `cura-build-environment/projects/python.cmake` file.
