### ISSUE TITLE
No CMAKE_Fortran_COMPILER could be found.

### ISSUE THREAD

**Issue by yingzhang1109** [Ultimaker/cura-build-environment#58]
when I do 
cmake .. -DCMAKE_INSTALL_PREFIX=/home/ying/cura-build -DCMAKE_BUILD_TYPE=Release
I have this error:
-- Building for Linux
-- The Fortran compiler identification is unknown
CMake Error at projects/openblas.cmake:3 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  CMakeLists.txt:42 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ying/source/build/CMakeFiles/CMakeOutput.log".
See also "/home/ying/source/build/CMakeFiles/CMakeError.log".

Can anyone help me for that? Thanks in advance.
I have Ubuntu 18.04

**Comment by LipuFei** [comment]
Hi  @yingzhang1109, it's probably missing gfortran. Could you install gfortran, for example via `apt install gfortran`, and try again?

**Comment by yingzhang1109** [comment]
> Hi @yingzhang1109, it's probably missing gfortran. Could you install gfortran, for example via `apt install gfortran`, and try again?

It works! Thanks a lot!

**Comment by Ghostkeeper** [comment]
Fortran is necessary in order to build Scipy.

**Comment by Atomzdq** [comment]
@LipuFei How to solve this problem on mac osx? I don't know how to install gfortran on max os.

**Comment by Ghostkeeper** [comment]
Maybe [`brew install gfortran`](https://brewformulas.org/Gfortran)?

**Comment by LipuFei** [comment]
@Atomzdq @Ghostkeeper has the answer for you.

**Comment by Atomzdq** [comment]
@LipuFei @Ghostkeeper Thanks! But a new problem happened:**The Fortran compiler

    "/usr/local/bin/gfortran"

  is not able to compile a simple test program.**

How to solve it? I'm sorry for many questions.

**Comment by LipuFei** [comment]
Need more information on that. Do you have the error message about why it failed?

**Comment by Atomzdq** [comment]
@LipuFei    This is the info:

**CMake Error at /Applications/CMake.app/Contents/share/cmake-3.13/Modules/CMakeTestFortranCompiler.cmake:45 (message):
  The Fortran compiler

    "/usr/local/bin/gfortran"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/zhou/Documents/cura-build-environment-master/build/CMakeFiles/CMakeTmp
    
    Run Build Command:"/usr/bin/make" "cmTC_54259/fast"
    /Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_54259.dir/build.make CMakeFiles/cmTC_54259.dir/build
    Building Fortran object CMakeFiles/cmTC_54259.dir/testFortranCompiler.f.o
    /usr/local/bin/gfortran    -c /Users/zhou/Documents/cura-build-environment-master/build/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_54259.dir/testFortranCompiler.f.o
    Linking Fortran executable cmTC_54259
    /Applications/CMake.app/Contents/bin/cmake -E cmake_link_script CMakeFiles/cmTC_54259.dir/link.txt --verbose=1
    /usr/local/bin/gfortran      CMakeFiles/cmTC_54259.dir/testFortranCompiler.f.o  -o cmTC_54259 
    ld: unexpected token: !tapi-tbd-v3 file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
    collect2: error: ld returned 1 exit status
    make[1]: *** [cmTC_54259] Error 1
    make: *** [cmTC_54259/fast] Error 2
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  projects/openblas.cmake:3 (enable_language)
  CMakeLists.txt:42 (include)


-- Configuring incomplete, errors occurred!
See also "/Users/zhou/Documents/cura-build-environment-master/build/CMakeFiles/CMakeOutput.log".
See also "/Users/zhou/Documents/cura-build-environment-master/build/CMakeFiles/CMakeError.log".**

**Comment by LipuFei** [comment]
I think this has something to do with the differences between `clang` from Mac OS X or `gcc` and `gfortran` from homebrew. AFAIK, Simply put, if you want to compile and link a library against another library that's built with MacOSX `clang`, your library needs to be compiled with `clang` as well. The same for `gcc` and `gfortran` from homebrew: for example, if you compile openssl with `gcc` and then compile `Qt` with `clang` and want to link against the gcc-compiled openssl, it won't work. Both of them need to be compiled with the same tool set.

**Comment by bxumn** [comment]
I had a similar but slightly different problem, and I tried 
apt install gfortran
brew install gfortran
clabg install gfortran

All did not work:
ERROR cmake configure failed
check cmake log files and try again
Boya-Xiong-2:charmm_build BoyaXiong$ apt install gfortran
Unable to locate an executable at "/Library/Java/JavaVirtualMachines/jdk-12.jdk/Contents/Home/bin/apt" (-1)
Boya-Xiong-2:charmm_build BoyaXiong$ brew install gfortran
-bash: brew: command not found
Boya-Xiong-2:charmm_build BoyaXiong$ clang install gfortran
clang: error: no such file or directory: 'install'
clang: error: no such file or directory: 'gfortran'
clang: error: no input files

Any idea what to do? Thank you!!

**Comment by LipuFei** [comment]
Hi @bxumn , looks like you are on Mac. You need to install Homebrew (https://brew.sh/) in order to use `brew`.

**Comment by jakesyl** [comment]
thanks!

**Comment by Mahya995** [comment]
Hello
I received this error when using CMake:

Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.

The Fortran compiler identification is unknown

CMake Error at CMakeLists.txt:16 (PROJECT):
No CMAKE_Fortran_COMPILER could be found
 

I would be grateful if you could help me.

**Comment by Ghostkeeper** [comment]
Which Fortran compiler did you install, Mahya995?
