### ISSUE TITLE
Could not extract tarball filename from url:

### ISSUE THREAD

**Issue by AlexanderLeeeeee** [Ultimaker/cura-build-environment#61]
CMake Error at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1401 (message):
  Could not extract tarball filename from url:
https://download.qt.io/archive/qt/5.10/5.10.1/single/qt-everywhere-src-5.10.1.tar.xz
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1805 (_ep_add_download_command)
  projects/qt.cmake:74 (ExternalProject_Add)
  CMakeLists.txt:42 (include)

I can use this link with "wget" on terminal, but it will call error if i straightly use Cmake.

**Comment by LipuFei** [comment]
Hi @AlexanderLeeeeee , you need to use at least cmake 3.6.

**Comment by AlexanderLeeeeee** [comment]
Thanks, but here comes more errors.

CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:174 (file):
  file failed to open for writing (Permission denied):

    /usr/cura-build-environment-master/build/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


CMake Error: Could not open file for write in copy operation /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:186 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdC
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdC
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdC
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdC
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdC
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdC
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdC
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdC
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:737 (file):
  file failed to open for writing (Permission denied):

    /usr/cura-build-environment-master/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:737 (file):
  file failed to open for writing (Permission denied):

    /usr/cura-build-environment-master/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:112 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


-- The C compiler identification is unknown
CMake Error: Could not open file for write in copy operation /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CMakeCCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCCompiler.cmake:192 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


CMake Error: Could not find cmake module file: /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CMakeCCompiler.cmake
CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdCXX
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdCXX
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdCXX
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdCXX
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdCXX
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdCXX
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdCXX
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:161 (file):
  file problem creating directory:
  /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CompilerIdCXX
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:31 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:737 (file):
  file failed to open for writing (Permission denied):

    /usr/cura-build-environment-master/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:737 (file):
  file failed to open for writing (Permission denied):

    /usr/cura-build-environment-master/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCompilerId.cmake:51 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:107 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:1 (project)


-- The CXX compiler identification is unknown
CMake Error: Could not open file for write in copy operation /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CMakeCXXCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:190 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


CMake Error: Could not find cmake module file: /usr/cura-build-environment-master/build/CMakeFiles/3.13.4/CMakeCXXCompiler.cmake
-- Check for working C compiler: /usr/bin/cc
CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:25 (file):
  file failed to open for writing (Permission denied):

    /usr/cura-build-environment-master/build/CMakeFiles/CMakeTmp/testCCompiler.c
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:37 (try_compile):
  Unknown extension ".c" for file

    /usr/cura-build-environment-master/build/CMakeFiles/CMakeTmp/testCCompiler.c

  try_compile() works only for enabled languages.  Currently these are:

    C CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Check for working C compiler: /usr/bin/cc -- broken
CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:48 (file):
  file failed to open for writing (Permission denied):

    /usr/cura-build-environment-master/build/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


CMake Error at /usr/cmake/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:1 (project)


-- Configuring incomplete, errors occurred!

**Comment by LipuFei** [comment]
Sorry to mention, but could you try cmake version between 3.6 and 3.11? There could be some problem with cmake 3.12 and higher.

**Comment by Ghostkeeper** [comment]
We're having some trouble building with CMake 3.12 ourselves as well.

**Comment by LipuFei** [comment]
The current `master` branch can now be built with CMake 3.12+. I'll close this ticket. @AlexanderLeeeeee If you still encounter similar CMake issues, feel free to reopen it.
