### ISSUE TITLE
Linking CXX shared library Savitar.so

### ISSUE THREAD

**Issue by JithuPG** [Ultimaker/cura-build-environment#63]
/usr/bin/ld: /usr/local/lib/libpython3.5m.a(ceval.o): relocation R_X86_64_PC32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/python_module_Savitar.dir/build.make:310: recipe for target 'Savitar.so' failed

is there any thing Missing ??

![screen-shot](https://user-images.githubusercontent.com/10563956/55091629-36daa400-50d7-11e9-9049-770d1973f01e.png)

**Comment by Ghostkeeper** [comment]
You could try recompiling with `-fPIC`.

In general though you must be careful to make sure you use the same compiler as what your CPython was compiled with. I hope you're using GCC? Maybe the version is wrong?

**Comment by JithuPG** [comment]
Thank you for your reply i will try recompiling with -fPIC 👍
