### ISSUE TITLE
4.4.x: Numpy-STL missing in AppImage

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/cura-build-environment#74]
In the AppImage I received from @rburema I can't find NumPy-STL. Can you confirm?

![image](https://user-images.githubusercontent.com/1847437/68955070-83d5cc80-07c5-11ea-9da9-ee49b0c4f7cd.png)

**Comment by Ghostkeeper** [comment]
Yeah can confirm. This has been going on for a while.

**Comment by LipuFei** [comment]
Fixed in https://github.com/Ultimaker/cura-build/commit/d7dfef08a62e7bac276afd9b42e42ad93b377f1f
