### ISSUE TITLE
docker pull fails

### ISSUE THREAD

**Issue by dickshaydle** [Ultimaker/cura-build-environment#75]
docker fails when trying to install the cura-build-environment container from docker hub:

```bash
>> docker pull --all-tags ultimaker/cura-build-environment   
Error response from daemon: repository ultimaker/cura-build-environment not found: name unknown: repository name not known to registry
```

**Comment by LipuFei** [comment]
Hi @dickshaydle , the docker image is not yet publicly available. For now, you need to build it yourself. You can find the build information in `README`. If the information is not correct, please let us know. We will update/correct it.

**Comment by LipuFei** [comment]
Hi @dickshaydle , I have just added GitHub Actions for this repository which will build and upload the CentOS-based docker image to dockerhub. Now you can use `docker pull ultimaker/cura-build-environment` to get the latest CentOS image built with the `master` branch.

**Comment by LipuFei** [comment]
I'll close this ticket.
