### ISSUE TITLE
make -j6 is not working on win10

### ISSUE THREAD

**Issue by yingzhang1109** [Ultimaker/cura-build-environment#8]
as the title, is there any command could do the same thing in windows 10 like make -j6?

**Comment by Ghostkeeper** [comment]
According to this thread, there is no such option: http://stackoverflow.com/questions/601970/how-do-i-utilise-all-the-cores-for-nmake

The answers there list a few alternatives. In particular, the NMake Makefiles JOM generator looks promising.

**Comment by yingzhang1109** [comment]
@Ghostkeeper  do you know how to use NMake Makefiles JOM generator? I do have this, but it seems that nmake -j6 is still not working

**Comment by awhiemstra** [comment]
Jom is a separate tool can be installed and used with any NMake project, as far as I recall. In any case, you are not going to get much out of running these build scripts with multiple jobs as the actual project building still happens with a single job. I have some ideas about changing that, but it is not really high on my priority list.

**Comment by LipuFei** [comment]
@yingzhang1109 There is no `-j` option for `nmake`. You can run `nmake /?` to see all the options. It is not possible to tell `nmake` to build in parallel. But from this stackoverflow post, seems like you can tell `cl` to compile multiple files at the same time, but it is very limited of course.
https://stackoverflow.com/questions/601970/how-do-i-utilise-all-the-cores-for-nmake
