### ISSUE TITLE
sqlite3 build fails due to wrong automake version

### ISSUE THREAD

**Issue by jellespijker** [Ultimaker/cura-build-environment#80]
When running on a Arch based distro, building fails because the version of `automake` is hardcoded in  the `Makefile`. Removing the version `-1.15` from line 251 `AUTOMAKE = ${SHELL} /home/peer23peer/projects/Cura/cura-build-environment/build/sqlite3-prefix/src/sqlite3/missing automake-1.15` allows the build to continue.

**Comment by Ghostkeeper** [comment]
This is a bug in SQLite's build system that we can't really fix. I'd advise to report the bug to the SQLite developers (as per instructions [here](https://www.sqlite.org/src/wiki?name=Bug+Reports)). However ironically their database of existing bug reports seems to be broken so you can't see whether it has been reported before.
