### ISSUE TITLE
Downloading Qt 5.10.1 fails

### ISSUE THREAD

**Issue by jellespijker** [Ultimaker/cura-build-environment#82]
Qt moved the archive. The new url is https://download.qt.io/new_archive/qt/5.10/5.10.1/single/qt-everywhere-src-5.10.1.tar.xz

**Comment by Ghostkeeper** [comment]
Thanks for the report! I verified this; the original page now shows a 404 page. The new one provides the download and the MD5 checksum is still the same.

I think we didn't notice this since we haven't needed to change any of our dependencies recently.
