### ISSUE TITLE
Installing slycot on Anaconda3 for python 3.8 usage in Windows 10. 

### ISSUE THREAD

**Issue by Squidward-Tentacle** [Ultimaker/cura-build-environment#87]
I’m trying to install slycot on Anaconda3. I downloaded gfortran for FORTRAN compiler and it’s still not working. I’ve pasted below what error pops up on my window. Please help I’ve been googling for a while and I can’t figure it out! 

(base) PS C:\Users\kakis> pip install slycot
Collecting slycot
  Using cached slycot-0.4.0.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy in c:\users\kakis\anaconda3\lib\site-packages (from slycot) (1.18.1)
Building wheels for collected packages: slycot
  Building wheel for slycot (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\kakis\anaconda3\python.exe' 'C:\Users\kakis\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\kakis\AppData\Local\Temp\tmp234sqtun'
       cwd: C:\Users\kakis\AppData\Local\Temp\pip-install-dqnc0dl6\slycot
  Complete output (58 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is MSVC 19.16.27026.1
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x86/cl.exe - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- The Fortran compiler identification is Flang
  CMake Error at CMakeLists.txt:4 (ENABLE_LANGUAGE):
    The CMAKE_Fortran_COMPILER:

      C:/Users/kakis/anaconda3/Library/bin/flang.exe

    is not a full path to an existing compiler tool.

    Tell CMake where to find the compiler by setting either the environment
    variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
    path to the compiler, or to the compiler name if it is in the PATH.

  -- Configuring incomplete, errors occurred!
  See also "C:/Users/kakis/AppData/Local/Temp/pip-install-dqnc0dl6/slycot/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/kakis/AppData/Local/Temp/pip-install-dqnc0dl6/slycot/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  FC ('-DCMAKE_Fortran_COMPILER=', 'C:/Users/kakis/anaconda3/Library/bin/flang.exe')
  F2PY ('-DF2PY_EXECUTABLE=', 'C:/Users/kakis/anaconda3/Scripts/f2py.exe')
  NUMPY_INCLUDE ('-DNumPy_INCLUDE_DIR=', 'C:/Users/kakis/anaconda3/Include')
  ['-DSLYCOT_VERSION:STRING=0.4.0', '-DGIT_REVISION:STRING=ac0944b363a6cfcc0c3d5128cdd484d74173aa3b', '-DISRELEASE:STRING=True', '-DFULL_VERSION=0.4.0.gitac0944b', '-GNMake Makefiles', '-DCMAKE_Fortran_COMPILER=C:/Users/kakis/anaconda3/Library/bin/flang.exe', '-DF2PY_EXECUTABLE=C:/Users/kakis/anaconda3/Scripts/f2py.exe', '-DNumPy_INCLUDE_DIR=C:/Users/kakis/anaconda3/Include', '-DCMAKE_Fortran_SIMULATE_VERSION=5.0.0', '-DCMAKE_Fortran_COMPILER_ID=Flang', '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON']

  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 v141)" generator - failure
  --------------------------------------------------------------------------------

  ********************************************************************************
  scikit-build could not get a working generator for your system. Aborting build.

  Building windows wheels for Python 3.7 requires Microsoft Visual Studio 2017.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

  ********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for slycot
Failed to build slycot
ERROR: Could not build wheels for slycot which use PEP 517 and cannot be installed directly

>

**Comment by Ghostkeeper** [comment]
This repository is a build script for the dependencies of [Cura](https://github.com/Ultimaker/Cura/), a slicer application for 3D printing. It's got nothing to do with Slycot.

Please report your issue here: https://github.com/python-control/Slycot/issues
